### ISSUE TITLE
Only showing "getting ready"

### ISSUE THREAD

**Issue by naturekid72** [ad/pwnmothership#1]
It just shows getting ready, the demo data works but what am I doing wrong?

**Comment by ad** [comment]
Maybe you did not set main.plugins.pwnmothership.api_url = "https://your-pwnmothership-address/api/set" (check readme)

**Comment by naturekid72** [comment]
I did set it. 

main.plugins.pwnmothership.enabled = true
main.plugins.pwnmothership.api_url = "https://192.168.178.56/api/set"

**Comment by ad** [comment]
try http://192.168.178.56/api/set (not secure address)

or http://192.168.178.56:8080/api/set if you run on :8080 port

**Comment by naturekid72** [comment]
Do I always have to start it in the mothershipfolder with pwnmothership --addr=:8082
do i set the api to 8080 or 8082?

**Comment by naturekid72** [comment]
changed it to 8080

Big:~/pwnmothership# ./pwnmothership
2022/08/04 12:35:04 [INFO] static files will be read from statik bindata
2022/08/04 12:35:04 start listening on :8080
2022/08/04 12:35:18 /ui file does not exist
2022/08/04 12:35:19 /ui file does not exist
2022/08/04 12:35:20 /ui file does not exist
2022/08/04 12:35:21 /ui file does not exist
2022/08/04 12:35:22 /ui file does not exist
2022/08/04 12:35:23 /ui file does not exist
2022/08/04 12:35:23 /null file does not exist

**Comment by ad** [comment]
I've updated code to Go 1.18, try rebuild now.

if you start it on port 8082, you should update address in config, for example:
main.plugins.pwnmothership.api_url = "http://192.168.178.56:8082/api/set"

**Comment by naturekid72** [comment]
build github.com/ad/pwnmothership: cannot find module for path embed

**Comment by ad** [comment]
pwnmothership on master via 🐹 v1.18.5 via 🐍 v3.8.9 
➜ git pull
Already up to date.

pwnmothership on master via 🐹 v1.18.5 via 🐍 v3.8.9 
➜ go build .                           

pwnmothership on master via 🐹 v1.18.5 via 🐍 v3.8.9 
➜ ./pwnmothership -addr=:8082
2022/08/04 14:26:51 start listening on :8082
